### ISSUE TITLE
 关于新增功能

### ISSUE THREAD

**Issue by lhn217** [chenmingxiang110/SimpleChinese2#1]
可否新增拼音文字相互转换的功能？

**Comment by chenmingxiang110** [comment]
你好，谢谢你的建议。拼音文字互相转换是个比较常见的NLP相关任务，我应该会在下次升级时新增该功能。新增后会在该issue通知您。

**Comment by chenmingxiang110** [comment]
你好！该功能已更新，如需使用请下载0.2.10版。如果想单独使用拼音文字互相转换的功能，也可以只安装simplepinyin包。
