### ISSUE TITLE
关于文件下载

### ISSUE THREAD

**Issue by John-McCartney** [chenmingxiang110/SimpleChinese2#3]
作者你好，我在下载词向量文件和pinyin文字词表文件时使用google drive遇到了困难，不知能否提供类似百度网盘之类的下载途径？

**Comment by chenmingxiang110** [comment]
谢谢你对项目的关注

Mingxiang Chen

730 Escondido Rd,

Stanford, California 94305
650-441-8408


John-McCartney ***@***.***> 于2021年9月7日周二 下午8:39写道：

**Comment by chenmingxiang110** [comment]
抱歉前一封是误发邮件，感谢你对项目的关注！

词向量文件下载地址如下：
链接: https://pan.baidu.com/s/1At0oLTgF6_U6Kq1qdJ63lw  密码: w0r3
拼音文字词表地址如下：
链接: https://pan.baidu.com/s/10Bpm7ZY_6_H_hahRJmQ9Jw  密码: eoma

如果下载有问题，可以通过邮箱联系我。以上地址将在晚些时候更新于github项目中。我真诚地希望这个项目可以帮助到你，如果可以的话，能否帮我点一个star呢？非常感谢

**Comment by John-McCartney** [comment]
感谢您的回复！祝您工作顺利！
