### ISSUE TITLE
请问下：怎样生成自己的 pinyin文字词表文件？

### ISSUE THREAD

**Issue by haha010508** [chenmingxiang110/SimpleChinese2#5]
在使用过程中，发现有些词不在词表文件，请问如何生成自己的词表文件？

**Comment by chenmingxiang110** [comment]
抱歉，Synonym不支持添加词语

参考
[https://github.com/chatopera/Synonyms
Frequently Asked Questions (FAQ) 问题1](https://github.com/chatopera/Synonyms/issues/5)

**Comment by haha010508** [comment]
多谢，但是我说的是这个文件，input_dict_nt_max.pickle， 我们说的是一个东西吗？

**Comment by chenmingxiang110** [comment]
Line 94 in https://github.com/chenmingxiang110/SimpleChinese2/blob/main/simplepinyin/lm.py
